export const initialClientStatus=()=>({state:'unavailable',reason:'host-unreachable',auth:'unconfirmed',connected:false});
const reasons={
 'launcher-config-required':'Launcher configuration requires scratch, runtime, Electron and provider paths',
 'launcher-mode-invalid':'Launcher mode must be scratch or route-b',
 'route-b-desktop-home-invalid':'The desktop settings HOME must be an absolute path',
 'route-b-shared-probe-denied':'Route B cannot use the shared scratch database probe',
 'route-b-custom-cipher-env-unsupported':'A custom credential cipher environment override is unsupported',
 'official-host-missing':'The extracted official Host is missing or unreadable',
 'official-host-subtree-mismatch':'The extracted official Host differs from the verified runtime; startup stopped',
 'official-artifact-mismatch':'The official Host or CLI differs from the verified runtime; startup stopped',
 'route-b-temp-socket-path-too-long':'Route B stopped before launch: scratch Unix socket path is too long',
 'route-b-retry-disabled':'Route B stopped; automatic retry is disabled',
 'status-query-failed':'Official read-only service initialization failed; launcher stopped',
 'route-b-authenticated-read-only':'Official account authenticated · shared sessions are read-only',
 'route-b-read-only-zero-model-requests':'Shared sessions are read-only · model requests disabled',
 'official-account-signed-out-stop':'Official account signed out; Route B stopped without retry',
 'official-account-reauthentication-required':'Official account requires reauthentication; Route B stopped',
 'official-credential-recovery-observed':'Official credential recovery detected; Route B stopped',
 'not-connected':'Not connected',connecting:'Connecting to official runtime…',
 'installation-missing':'Official ZCode installation was not found',
 'installation-ambiguous':'Multiple installations found; configure the intended App path',
 'helper-missing':'The official Electron helper is missing',
 'runtime-missing':'The official runtime bundle is missing',
 'provider-config-missing':'The official provider configuration is missing',
 'installation-metadata-invalid':'The App metadata does not identify official ZCode',
 'launcher-unusable':'The official Electron Node launcher could not be verified',
 'workspace-required':'Configure a dedicated workspace before connecting',
 'workspace-missing':'The configured workspace does not exist',
 'official-auth-source-missing':'Restricted: protocol connected; official request authentication unavailable',
 'runtime-unverified':'Restricted: this installation tuple has not been verified',
 'host-unreachable':'Host unavailable; refresh after reconnecting',
 disposed:'Connection disposed', 'request-timeout':'Official request timed out; execution state is unknown',
 'protocol-invalid':'Official protocol frame was invalid', 'transport-eof':'Official runtime disconnected',
 'transport-error':'Official runtime transport failed', 'launch-failed':'Official runtime launch failed',
 'unsupported-platform':'This bridge currently supports macOS',
 'runtime-rejected':'Official runtime rejected the request',
 'runtime-incompatible':'Core protocol incompatibility: new side effects are stopped; reconnect to retry',
 'capabilities-invalid':'Official capability response is incompatible','sessions-invalid':'Official session response is incompatible',
};
export function statusText(state){return reasons[state.reason]??'Unavailable: connection state is unconfirmed'}
