import {test} from 'node:test';import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';import {buildSync} from 'esbuild';import vm from 'node:vm';import {createRequire} from 'node:module';import {resolve} from 'node:path';
import {HostChannel,encodeFrame,decodeFrame} from '../packages/host/launcher/channel.mjs';
import {createExecutionRelay,EXECUTION_CALLS,EXECUTION_EVENTS,LauncherPeer} from '../packages/host/launcher/execution.mjs';
import {V4Conversation} from '../packages/host/conversation.mjs';
import {world,catalogRow,directory,tick} from './helpers/conversation-runtime.mjs';
import {MockPeer} from './helpers/zcode-runtime-fixture.mjs';
const message=(text,id)=>({source:{kind:'user',rpcId:id},content:[{type:'text',text}]});
const settle=async agent=>{await tick();await Promise.all([...agent.dispatches]);await tick()};
const deferred=()=>Promise.withResolvers();
// Bundle the actual pinned official implementation in memory. No reference writes or copied proxy.
const official=(()=>{const root=resolve('reference/ZCode/packages/rpc/src');const source=buildSync({stdin:{contents:`export {ProxyChannel} from '${root}/proxy-channel.ts';export {Emitter} from '${root}/foundation.ts';`,resolveDir:root},bundle:true,write:false,format:'cjs',platform:'node'}).outputFiles[0].text;const mod={exports:{}};vm.runInThisContext('(function(require,module,exports){'+source+'\n})')(createRequire(import.meta.url),mod,mod.exports);return mod.exports})();
function carrier({wrapEvent=false,ackGate}={}){
 const emitters=new Map(),eventArguments=[],ordinaryArguments=[],mock=new MockPeer();const key=target=>target?.workspaceIdentity??target?.workspacePath;
 const service={onDynamicConversationFrame(target){eventArguments.push(target);const k=key(target);let emitter=emitters.get(k);if(!emitter)emitters.set(k,emitter=new official.Emitter());return emitter.event},async subscribeConversationV4(payload){ordinaryArguments.push(payload);const result=await mock.request('v4/conversation/subscribe',{topic:'conversation/'+payload.sessionId});if(ackGate)await ackGate.promise;return result},resyncConversationV4:payload=>mock.request('v4/conversation/resync',{subscriptionId:payload.subscriptionId}),unsubscribeConversationV4:payload=>mock.request('v4/conversation/unsubscribe',payload)};
 mock.onNotification(event=>emitters.get('/execution')?.fire(event.params));
 const proxy=official.ProxyChannel.fromService(service),listeners=new Map();
 class Port extends EventEmitter{start(){queueMicrotask(()=>this.emit('message',{data:encodeFrame([200])}))}close(){}postMessage(bytes){const [header,body]=decodeFrame(bytes);if(header[0]===102){const release=proxy.listen({},header[3],body)(value=>this.emit('message',{data:encodeFrame([204,header[1]],value)}));listeners.set(header[1],release)}else if(header[0]===103){listeners.get(header[1])?.dispose();listeners.delete(header[1])}else if(header[0]===100){Promise.resolve(proxy.call({},header[3],body)).then(value=>this.emit('message',{data:encodeFrame([201,header[1]],value)}),error=>this.emit('message',{data:encodeFrame([202,header[1]],{message:error.message})}))}}}
 const channel=new HostChannel(new Port(),{allowCalls:new Set(EXECUTION_CALLS),allowEvents:EXECUTION_EVENTS});const frames=[];
 const relay=createExecutionRelay({workspacePath:'/execution',workspaceIdentity:'/execution',channel:wrapEvent?{call:(...args)=>channel.call(...args),listen:(svc,event,listener,arg)=>channel.listen(svc,event,listener,Array.isArray(arg)?arg:[arg])}:channel,emit:event=>frames.push(event)});
 return {relay,channel,frames,eventArguments,ordinaryArguments,mock,dispose(){relay.dispose();channel.close();for(const emitter of emitters.values())emitter.dispose()}};
}
test('Conversation runtime R1 carrier counterfactual crosses production HostChannel and official ProxyChannel: object=1 frame, array=0',async()=>{
 for(const wrapEvent of [true,false]){const c=carrier({wrapEvent});try{await c.relay.request('v4/conversation/subscribe',{topic:'conversation/'+c.mock.snapshot.sessionId});await tick();assert.equal(c.frames.length,wrapEvent?0:1);assert.equal(Array.isArray(c.eventArguments[0]),wrapEvent);assert.equal(c.ordinaryArguments[0].workspacePath,'/execution')}finally{c.dispose()}}
});
test('Conversation runtime R1 ACK reservation holds an early official frame across event-loop turns until onResult establishes baseline',async()=>{
 const ackGate=deferred(),c=carrier({ackGate});let receive;const launcher={state:{phase:'ready'},subscribe:()=>()=>{},onExecutionEvent:fn=>{receive=fn;return ()=>{}},execution:(...args)=>c.relay.request(...args)};c.relay.dispose(); // rebuild emit into real LauncherPeer
 const relay=createExecutionRelay({workspacePath:'/execution',workspaceIdentity:'/execution',channel:c.channel,emit:event=>{c.frames.push(event);receive(event)}});launcher.execution=(...args)=>relay.request(...args);const peer=new LauncherPeer(launcher);
 const conversation=new V4Conversation(peer,{address:{runtime:'zcode',authority:'official-host',workspace:'/execution',sessionId:c.mock.snapshot.sessionId},workspace:{workspacePath:'/execution',workspaceKey:'/execution'},connectionId:peer.connectionId,clientId:'test',runnable:true});
 try{const connecting=conversation.connect();await tick();await tick();assert.equal(c.frames.length,1);assert.equal(conversation.state.status,'connecting');ackGate.resolve();await connecting;await tick();assert.equal(conversation.state.status,'live');assert.ok(conversation.state.snapshot)}finally{ackGate.resolve();await conversation.cancel();peer.close();relay.dispose();c.dispose()}
});
test('Conversation runtime R1 A-M1 pre-dispatch ensurePeer failure is retryable not-sent; selection and deliberate first input still work',async()=>{
 const w=await world();try{const {sessionId}=await w.runtime.create();const agent=w.runtime.agents.get(sessionId),ensure=w.runtime.ensurePeer.bind(w.runtime);w.runtime.ensurePeer=async()=>{throw Object.assign(new Error('offline'),{code:'execution-unavailable'})};agent.followup(message('failed before send','pre'));await settle(agent);const old=Object.values(agent.record.operations)[0];assert.equal(old.state,'not-sent');assert.equal(agent.record.createCommandId,undefined);assert.equal(w.peer.calls.filter(c=>c.params?.type==='createSession').length,0);w.runtime.ensurePeer=ensure;await w.runtime.selectSession(sessionId,{provider:'zcode',model:'B/model_c'});agent.followup(message('deliberate retry','retry'));await settle(agent);assert.ok(agent.record.officialId);assert.equal(old.state,'not-sent');assert.equal(w.peer.calls.filter(c=>c.params?.type==='createSession').length,1)}finally{await w.runtime.dispose()}
});
test('Conversation runtime R1 A-M1 relay pre-validation rejection is not-sent and never an ambiguous create',async()=>{
 for(const kind of ['workspace','capacity','disposed']){const w=await world();try{const {sessionId}=await w.runtime.create();const agent=w.runtime.agents.get(sessionId),request=w.peer.request.bind(w.peer);const relay=createExecutionRelay({workspacePath:kind==='workspace'?'/other':'/execution',...(kind==='capacity'?{maxPending:0}:{}),emit(){},channel:{call(){throw Error('must not dispatch')},listen(){throw Error('must not listen')}}});if(kind==='disposed')relay.dispose();w.peer.request=(method,params,options)=>params?.type==='createSession'?relay.request(method,params):request(method,params,options);agent.followup(message('pre-validation failure','deny'));await settle(agent);assert.equal(Object.values(agent.record.operations)[0].state,'not-sent',kind);assert.equal(agent.record.createCommandId,undefined);w.peer.request=request;agent.followup(message('explicit retry','retry'));await settle(agent);assert.ok(agent.record.officialId);relay.dispose()}finally{await w.runtime.dispose()}}
});
test('Conversation runtime R1 B-4 terminal failed/rejected ACKs retain receipts and permit a new first input without auto-replay',async()=>{
 for(const status of ['failed','rejected']){const w=await world();try{const {sessionId}=await w.runtime.create();const agent=w.runtime.agents.get(sessionId),request=w.peer.request.bind(w.peer);let rejected=true;w.peer.request=(method,params,options)=>{if(params?.type==='createSession'&&rejected){rejected=false;const ack={commandId:params.commandId,status,reasonCode:'test.terminal',revisionAtDecision:0};w.peer.acks.set(params.commandId,ack);return Promise.resolve(ack)}return request(method,params,options)};agent.followup(message('first rejection','rejected'));await settle(agent);const old=Object.values(agent.record.operations)[0];assert.equal(old.state,status);assert.equal(agent.record.createCommandId,undefined);await w.runtime.recoverAll();assert.equal(w.peer.calls.filter(c=>c.method==='v4/commands/query').length,0);await w.runtime.selectSession(sessionId,{provider:'zcode',model:'B/model_c'});agent.followup(message('new deliberate first input','new'));await settle(agent);assert.ok(agent.record.officialId);assert.equal(old.ack.status,status);assert.equal(Object.keys(agent.record.operations).length,2)}finally{await w.runtime.dispose()}}
});
test('Conversation runtime R1 B-1 /alias official address survives /canonical native normalization and refreshed catalog/open',async()=>{
 const w=await world({catalog:async()=>directory([catalogRow('one','Alias title','/alias')])});const canonical=await w.ctx.workspaceRegistry.create('/canonical');const resolvePath=w.ctx.workspaceRegistry.resolveByPath;w.ctx.workspaceRegistry.resolveByPath=async path=>path==='/alias'?canonical:resolvePath(path);
 try{await w.runtime.refreshDirectory();const record=[...w.store.records.values()][0];assert.equal(record.workspace,'/alias');assert.equal(record.cwd,'/canonical');assert.equal(record.workspaceId,canonical.id);assert.equal(w.sessions.get(record.id).header.cwd,'/canonical');await w.runtime.refreshDirectory();assert.equal(w.store.records.size,1);assert.equal(w.runtime.absent.has(record.id),false);w.peer.registerSession('one');await w.runtime.open(record.id);await tick();assert.equal(w.runtime.info(record.id).officialAddress.workspace,'/alias');assert.equal(w.peer.calls.find(c=>c.method==='v4/conversation/subscribe').params.workspace.workspacePath,'/alias')}finally{await w.runtime.dispose()}
});
test('Conversation runtime R1 B-2 ENOENT during external absence removal cannot block disposal or directory publication',async()=>{
 let rows=[catalogRow('missing','Title','/missing')];const w=await world({catalog:async()=>directory(rows)});let published=0;w.runtime.publishDirectory=async()=>published++;w.ctx.workspaceRegistry.resolveByPath=async path=>{if(path==='/missing')throw Object.assign(new Error('gone'),{code:'ENOENT'});return undefined};
 try{await w.runtime.refreshDirectory();const record=[...w.store.records.values()][0];assert.ok(w.agents.has(record.id));rows=[];await w.runtime.refreshDirectory();assert.equal(w.agents.has(record.id),false);assert.equal(w.sessions.has(record.id),false);assert.ok(published>=2);assert.equal(w.peer.calls.filter(c=>c.method==='v4/command').length,0)}finally{await w.runtime.dispose()}
});
test('Conversation runtime R1 B-3 lost-ACK catalog import then adoption has one owner, original native identity and ledger',async()=>{
 let rows=[];const w=await world({catalog:async()=>directory(rows)});try{const {sessionId}=await w.runtime.create();const agent=w.agents.get(sessionId);w.peer.loseAck=true;agent.followup(message('once','original-rpc'));await settle(agent);const operation=Object.values(agent.record.operations)[0];const ack=w.peer.acks.get(operation.commandId);rows=[catalogRow(ack.result.sessionId,'Authoritative')];await w.runtime.refreshDirectory();const duplicate=[...w.store.records.values()].find(r=>r.id!==sessionId);assert.ok(duplicate?.imported);duplicate.operations.extra={commandId:'extra',type:'sendText',state:'accepted',requestId:'import-rpc'};
 await w.runtime.recoverAll();await tick();const owners=[...w.store.records.values()].filter(r=>r.officialId===ack.result.sessionId&&r.workspace==='/execution');assert.equal(owners.length,1);assert.equal(owners[0].id,sessionId);assert.equal(w.agents.has(duplicate.id),false);assert.equal(w.sessions.has(duplicate.id),false);assert.equal(w.runtime.info(duplicate.id).runtime,'zcode');await assert.rejects(w.runtime.create({sessionId:duplicate.id}),{code:'session/not-found'});assert.equal(w.agents.get(sessionId),agent);assert.equal(agent.record.operations[operation.commandId].requestId,'original-rpc');assert.equal(agent.record.operations.extra.requestId,'import-rpc');assert.equal(w.peer.calls.filter(c=>c.params?.type==='createSession').length,1);assert.ok(agent.record.retiredMirrors.some(r=>r.id===duplicate.id));await w.runtime.refreshDirectory();assert.equal([...w.store.records.values()].filter(r=>r.officialId===ack.result.sessionId).length,1);
 }finally{await w.runtime.dispose()}
});
test('Conversation runtime R1 ordering counterfactual: timing-only deferral loses a pre-ACK frame; explicit reservation retains it',async()=>{
 for(const timingOnly of [true,false]){const ackGate=deferred(),c=carrier({ackGate});let receive;const launcher={state:{phase:'ready'},subscribe:()=>()=>{},onExecutionEvent:fn=>{receive=fn;return ()=>{}},execution:(...args)=>c.relay.request(...args)};
 c.relay.dispose();const relay=createExecutionRelay({workspacePath:'/execution',workspaceIdentity:'/execution',channel:c.channel,emit:event=>{c.frames.push(event);receive(event)}});launcher.execution=(...args)=>relay.request(...args);const peer=new LauncherPeer(launcher);if(timingOnly)peer.receive=event=>setImmediate(()=>peer.deliver(event));
 const conversation=new V4Conversation(peer,{address:{runtime:'zcode',authority:'official-host',workspace:'/execution',sessionId:c.mock.snapshot.sessionId},workspace:{workspacePath:'/execution',workspaceKey:'/execution'},connectionId:peer.connectionId,clientId:'test',runnable:true});try{const connecting=conversation.connect();await tick();await tick();await tick();assert.equal(c.frames.length,1);ackGate.resolve();await connecting;await tick();assert.equal(conversation.state.snapshot!==null,!timingOnly)}finally{ackGate.resolve();await conversation.cancel();peer.close();relay.dispose();c.dispose()}}
});
test('Conversation runtime R1 B-3 adoption/publication serialization prevents a partially registered catalog import surviving retirement',async()=>{
 for(const unserialized of [true,false]){let rows=[];const w=await world({catalog:async()=>directory(rows)}),gate=deferred(),entered=deferred();try{const {sessionId}=await w.runtime.create();const original=w.agents.get(sessionId);w.peer.loseAck=true;original.followup(message('only once','rpc'));await settle(original);const ack=w.peer.acks.get(original.record.createCommandId);rows=[catalogRow(ack.result.sessionId)];
 if(unserialized)w.runtime.publishIdentity=action=>action();const register=w.ctx.agents.register;w.ctx.agents.register=async agent=>{if(agent.record.imported){entered.resolve();await gate.promise}return register(agent)};
 const catalog=w.runtime.refreshDirectory();await entered.promise;const recovery=w.runtime.recoverAll();await tick();await tick();if(!unserialized)assert.equal(original.record.officialId,'','ACK adoption is queued behind the partial import');gate.resolve();await catalog;await recovery;await tick();assert.equal(w.agents.size,unserialized?2:1);if(!unserialized){assert.equal(w.agents.get(sessionId),original);assert.equal(w.store.records.size,1)}assert.equal(w.peer.calls.filter(c=>c.params?.type==='createSession').length,1);
 }finally{gate.resolve();await w.runtime.dispose()}}
});
test('Conversation runtime R1 a queried terminal create outcome releases ambiguity without replay and retains the original receipt',async()=>{
 const w=await world();try{const {sessionId}=await w.runtime.create();const agent=w.agents.get(sessionId);w.peer.loseAck=true;agent.followup(message('unknown','unknown'));await settle(agent);const id=agent.record.createCommandId;w.peer.acks.set(id,{commandId:id,status:'failed',reasonCode:'official.denied',revisionAtDecision:0});await w.runtime.recoverAll();assert.equal(agent.record.createCommandId,undefined);assert.equal(agent.record.operations[id].ack.status,'failed');assert.equal(w.peer.calls.filter(c=>c.params?.type==='createSession').length,1);await w.runtime.selectSession(sessionId,{provider:'zcode',model:'B/model_c'});assert.equal(w.peer.calls.filter(c=>c.params?.type==='switchModelConfig').length,0)}finally{await w.runtime.dispose()}
});
