import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {world,directory,catalogRow,tick} from './helpers/conversation-runtime.mjs';
const acceptance=JSON.parse(readFileSync(new URL('./fixtures/conversation-runtime-repair2/acceptance.json',import.meta.url)));
const message=(text,id)=>({source:{kind:'user',rpcId:id},content:[{type:'text',text}]});
const settle=async agent=>{await tick();await Promise.all([...agent.dispatches]);await tick()};
const deferred=()=>Promise.withResolvers();
function record(legacy=false){return {id:'acceptance-mirror',officialId:acceptance.snapshot.sessionId,workspace:'/execution',authority:'official-host',imported:true,...(legacy?structuredClone(acceptance.legacy):{operations:structuredClone(acceptance.legacy.operations),events:[]}),...(legacy?{snapshot:structuredClone(acceptance.snapshot)}:{})}}
function assertAnswer(agent,events){
 const source=acceptance.snapshot.rows.window.find(row=>row.kind==='userInput');
 const user=events.find(event=>event.type==='user/message'&&event.data.message===undefined&&event.data.content.some(part=>part.text===source.text));assert.ok(user,'official user row must render');
 const operation=agent.record.operations[source.sourceCommandId];assert.equal(user.data.source.rpcId,operation.requestId);assert.equal(operation.state,'projected');
 const answers=events.filter(event=>event.type==='assistant/message').flatMap(event=>event.data.message.content.filter(part=>part.type==='text').map(part=>part.text));assert.deepEqual(answers,acceptance.snapshot.rows.window.filter(row=>row.kind==='assistantText').map(row=>row.text));
 const reasoning=events.filter(event=>event.type==='assistant/message').flatMap(event=>event.data.message.content.filter(part=>part.type==='reasoning').map(part=>part.text));assert.equal(reasoning.length,1);
 assert.notEqual(user.data.id,events.find(event=>event.type==='assistant/message'&&event.data.message.content.some(part=>part.type==='text')).data.message.id);
}
test('Conversation runtime R2 P1 exact acceptance snapshot: shared entityIds render distinct user/reasoning/final rows and project the receipt',async()=>{
 assert.equal(acceptance.snapshot.rows.window[0].entityId,acceptance.snapshot.rows.window[1].entityId);assert.equal(acceptance.snapshot.rows.window[2].entityId,acceptance.snapshot.rows.window[3].entityId);
 const r=record(),w=await world({records:[r]});try{w.peer.snapshot=structuredClone(acceptance.snapshot);w.peer.snapshots.set(r.officialId,w.peer.snapshot);const agent=await w.runtime.register(r);await agent.connect();await tick();assertAnswer(agent,r.events);const count=r.events.length;w.peer.publish(w.peer.snapshot);await tick();assert.equal(r.events.length,count,'repeat snapshot cannot duplicate rows');assert.deepEqual(r.snapshot.rows.window.map(row=>row.entityId),acceptance.snapshot.rows.window.map(row=>row.entityId),'official targeting identity must remain canonical')}finally{await w.runtime.dispose()}
});
test('Conversation runtime R2 P1 persisted legacy acceptance projection recovers omitted rows in a valid replay segment on next snapshot',async()=>{
 const r=record(true),before=structuredClone(r.events),w=await world({records:[r]});try{w.peer.snapshot=structuredClone(acceptance.snapshot);w.peer.snapshots.set(r.officialId,w.peer.snapshot);const agent=await w.runtime.register(r),session=agent.session;const previousSeq=session.seq;let reopened=0;w.runtime.subscribeHistory(r.id,()=>reopened++);await agent.connect();await tick();assertAnswer(agent,r.events.filter(event=>event.seq>=(r.historyStartSeq??0)));assert.ok(r.historyStartSeq>=previousSeq);assert.equal(r.historyGeneration,1);assert.equal(reopened,1);assert.equal(w.agents.get(r.id),agent);assert.equal(w.sessions.get(r.id),session);assert.deepEqual(r.events.slice(0,before.length),before);const length=r.events.length;w.peer.publish(w.peer.snapshot);await tick();assert.equal(r.events.length,length);assert.equal(w.peer.calls.filter(call=>call.method==='v4/command').length,0)}finally{await w.runtime.dispose()}
});
test('Conversation runtime R2 phase-2 open paused in normalization cannot resurrect a retired catalog import after ACK adoption',async()=>{
 let rows=[];const w=await world({catalog:async()=>directory(rows)}),gate=deferred(),entered=deferred();let opening;
 try{const {sessionId}=await w.runtime.create();const original=w.agents.get(sessionId);w.peer.loseAck=true;original.followup(message('only mock create','native-first'));await settle(original);const ack=w.peer.acks.get(original.record.createCommandId);rows=[catalogRow(ack.result.sessionId)];await w.runtime.refreshDirectory();const duplicate=[...w.store.records.values()].find(r=>r.id!==sessionId);assert.ok(duplicate.imported);
 const normalize=w.runtime.normalizeRecord.bind(w.runtime);w.runtime.normalizeRecord=async(record,...args)=>{if(record===duplicate){entered.resolve();await gate.promise}return normalize(record,...args)};
 opening=w.runtime.open(duplicate.id).then(value=>({value}),error=>({error}));await entered.promise;await w.runtime.recoverAll();await tick();assert.equal(w.store.records.has(duplicate.id),false);assert.equal(w.agents.has(duplicate.id),false);gate.resolve();const result=await opening;assert.equal(result.error?.code,'session/not-found');assert.equal(w.agents.size,1);assert.equal(w.sessions.size,1);assert.equal(w.agents.get(sessionId),original);assert.equal(w.runtime.disposers.has(duplicate.id),false);assert.equal(w.peer.subscriptions.size,1);assert.equal(w.peer.calls.filter(call=>call.method==='v4/conversation/subscribe').length,1,'only the preserved original mirror may subscribe');assert.equal(w.peer.calls.filter(call=>call.params?.type==='createSession').length,1);
 }finally{gate.resolve();await opening;await w.runtime.dispose()}
});
test('Conversation runtime R2 P1 row-scoped streams/prefixes retain both shared-entity rows through disconnect and epoch replacement',async()=>{
 const r=record(),w=await world({records:[r]});try{
 const snapshot=structuredClone(acceptance.snapshot);snapshot.rows.window[0].state='running';snapshot.rows.window[2].text='thinking';snapshot.rows.window[2].state='streaming';snapshot.rows.window[3].text='a';snapshot.rows.window[3].state='streaming';snapshot.control.canStop=true;w.peer.snapshot=snapshot;w.peer.snapshots.set(r.officialId,snapshot);
 const agent=await w.runtime.register(r);await agent.connect();await tick();assert.equal(agent.streams.size,2);const keys=[...agent.streams.keys()];assert.notEqual(keys[0],keys[1]);w.peer.disconnect();assert.deepEqual(Object.keys(r.prefixes).sort(),keys.sort());assert.deepEqual(Object.values(r.prefixes).sort(),['a','thinking']);
 const completed=structuredClone(snapshot);completed.seq++;completed.rows.window[0].state='completedSuccess';completed.rows.window[2].text='thinking done';completed.rows.window[2].state='complete';completed.rows.window[3].text='a done';completed.rows.window[3].state='complete';completed.control.canStop=false;w.peer.snapshot=completed;w.peer.snapshots.set(r.officialId,completed);await agent.reconnect();await tick();
 const blocks=r.events.filter(event=>event.type==='assistant/message').flatMap(event=>event.data.message.content);assert.equal(blocks.filter(part=>part.type==='text').map(part=>part.text).join(''),'a done');assert.equal(blocks.filter(part=>part.type==='reasoning').map(part=>part.text).join(''),'thinking done');assert.deepEqual(r.prefixes,{});
 const firstIds=r.events.filter(event=>event.type==='assistant/message').map(event=>event.data.message.id);const replaced=structuredClone(completed);replaced.logEpoch='new-epoch';w.peer.publish(replaced);await tick();const current=r.events.filter(event=>event.seq>=r.historyStartSeq);const secondIds=current.filter(event=>event.type==='assistant/message').map(event=>event.data.message.id);assert.ok(secondIds.every(id=>!firstIds.includes(id)));assert.equal(current.filter(event=>event.type==='user/message').length,1);assert.equal(r.projectionIdentityVersion,2);assert.equal(w.peer.calls.filter(call=>call.method==='v4/command').length,0);
 }finally{await w.runtime.dispose()}
});
test('Conversation runtime R2 phase-2 adoption waits for an open acquiring native membership, then retires its only subscription',async()=>{
 let rows=[];const w=await world({catalog:async()=>directory(rows)}),gate=deferred(),entered=deferred();let opening,recovery;
 try{const {sessionId}=await w.runtime.create();const original=w.agents.get(sessionId);w.peer.loseAck=true;original.followup(message('mock once','rpc-first'));await settle(original);const ack=w.peer.acks.get(original.record.createCommandId);rows=[catalogRow(ack.result.sessionId)];await w.runtime.refreshDirectory();const duplicate=[...w.store.records.values()].find(record=>record.id!==sessionId);const workspace=w.workspaces.get(duplicate.workspaceId),attach=workspace.attachSession;workspace.attachSession=async id=>{if(id===duplicate.id){entered.resolve();await gate.promise}return attach(id)};
 opening=w.runtime.open(duplicate.id);await entered.promise;recovery=w.runtime.recoverAll();await tick();assert.equal(w.store.records.has(duplicate.id),true,'retirement waits for serialized native acquisition');gate.resolve();await opening;await recovery;await tick();assert.equal(w.store.records.size,1);assert.equal(w.agents.size,1);assert.equal(w.sessions.size,1);assert.equal(w.runtime.disposers.has(duplicate.id),false);assert.equal(w.peer.subscriptions.size,1);assert.equal(w.agents.get(sessionId),original);
 }finally{gate.resolve();await opening;await recovery;await w.runtime.dispose()}
});
