import {test} from 'node:test';import assert from 'node:assert/strict';import {world,catalogRow,directory,tick} from './helpers/s03-runtime.mjs';
import {installMirrorGuards} from '../packages/host/mirror-guards.mjs';
test('TRACE S03 external deletion plus stale catalog: native row unmounts, stale opening fails, no write/delete',async()=>{
 const replies=[];const w=await world({catalog:()=>new Promise(resolve=>replies.push(resolve))});try{const first=w.runtime.refreshDirectory();await tick();replies[0](directory([catalogRow()]));await first;const record=[...w.store.records.values()][0];const stale=w.runtime.refreshDirectory(),fresh=w.runtime.refreshDirectory();await tick();replies[2](directory([]));await fresh;replies[1](directory([catalogRow()]));await stale;assert.equal(w.runtime.agents.size,0);assert.equal([...w.workspaces.values()][0].sessionIds.length,0);const open=w.runtime.open(record.id);await tick();replies[3](directory([]));await assert.rejects(open,{code:'session/not-found'});assert.equal(w.peer.calls.filter(call=>call.method==='v4/command').length,0)}finally{await w.runtime.dispose()}
});
test('S03 open refreshes official title before hydration; rename writes officially and re-reads task title',async()=>{
 let rows=[catalogRow('one','Before')],reads=0;const w=await world({catalog:async()=>{reads++;return directory(rows)}});try{await w.runtime.refreshDirectory();const record=[...w.store.records.values()][0];w.peer.registerSession('one');rows=[catalogRow('one','External rename')];await w.runtime.open(record.id);await tick();assert.equal(record.events.findLast(event=>event.type==='session/title').data.title,'🅩 External rename');assert.equal(reads,2);
 const request=w.peer.request.bind(w.peer);w.peer.request=async(method,params,options)=>{if(params?.type==='renameSession')rows=[catalogRow('one',params.payload.title+' authoritative')];return request(method,params,options)};
 const result=await w.runtime.rename(record.id,'🅩 Requested');assert.equal(result.title,'🅩 Requested authoritative');assert.equal(w.peer.calls.find(call=>call.params?.type==='renameSession').params.payload.title,'Requested');assert.equal(w.peer.calls.filter(call=>call.params?.type==='deleteSession').length,0);
 }finally{await w.runtime.dispose()}
});
test('S03 native catalog projects imported empty-history rows visible and filters confirmed absence',async()=>{
 const emitted=[];const w=await world();const controller={list:async()=>({items:[{sessionId:'mirror',blank:true},{sessionId:'gone',blank:false},{sessionId:'native',blank:true}]}),rename:async()=>{},selectModel:async()=>{}};
 w.store.records.set('mirror',{id:'mirror',officialId:'official'});w.store.records.set('gone',{id:'gone'});w.runtime.absent.add('gone');const scope={sessionController:controller,effect(){},get(){}};installMirrorGuards({inject:(keys,apply)=>apply(keys.includes('workspaceController')?{workspaceController:{},effect(){}}:scope),emit:(name,item)=>emitted.push({name,item})},w.runtime);
 assert.deepEqual((await controller.list()).items,[{sessionId:'mirror',blank:false},{sessionId:'native',blank:true}]);await w.runtime.publishDirectory();assert.ok(emitted.some(value=>value.item.sessionId==='mirror'&&!value.item.blank));assert.ok(!emitted.some(value=>value.item.sessionId==='gone'));await w.runtime.dispose();
});
test('S03 missing official workspace keeps a native ungrouped title row and fails open without a command',async()=>{
 const w=await world({catalog:async()=>directory([catalogRow('gone-dir','Still official','/missing')])});const resolve=w.ctx.workspaceRegistry.resolveByPath;w.ctx.workspaceRegistry.resolveByPath=async path=>{if(path==='/missing')throw Object.assign(new Error('missing'),{code:'ENOENT'});return resolve(path)};
 try{await w.runtime.refreshDirectory();const record=[...w.store.records.values()][0];assert.ok(w.runtime.agents.has(record.id));assert.equal(record.events.findLast(event=>event.type==='session/title').data.title,'🅩 Still official');assert.equal(record.workspaceUnavailable,true);await assert.rejects(w.runtime.open(record.id),{code:'session/workspace-unavailable'});assert.equal(w.peer.calls.filter(call=>call.method==='v4/command').length,0);
 w.ctx.workspaceRegistry.resolveByPath=resolve;await w.runtime.open(record.id);assert.equal(record.workspaceUnavailable,undefined);assert.ok(w.workspaces.get(record.workspaceId).sessionIds.includes(record.id));
 }finally{await w.runtime.dispose()}
});
